# Model hyperparameters
vocab_size: 10000
context_length: 1024
d_model: 768
num_layers: 12
num_heads: 12
d_ff: 3072
rope_theta: 10000.0

# Benchmarking parameters
batch_size: 4
warmup_steps: 5
repeats: 10
forward_only: False
device: "cuda"
